// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/albums/:albumId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/albums/[albumId]/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/albums/[albumId]/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/albums/[albumId]/index.put').default>>>>
    }
    '/api/albums/:albumId/photos/:photoId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/albums/[albumId]/photos/[photoId].delete').default>>>>
    }
    '/api/albums': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/albums/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/albums/index.post').default>>>>
    }
    '/api/auth/github': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/github.get').default>>>>
    }
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
    }
    '/api/logout': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logout.get').default>>>>
    }
    '/api/photos/:photoId/albums': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/[photoId]/albums.get').default>>>>
    }
    '/api/photos/:photoId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/[photoId]/index.delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/[photoId]/index.put').default>>>>
    }
    '/api/photos/:photoId/livephoto': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/[photoId]/livephoto.get').default>>>>
    }
    '/api/photos/:photoId/reactions': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/[photoId]/reactions').default>>>>
    }
    '/api/photos/check-duplicate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/check-duplicate.post').default>>>>
    }
    '/api/photos/exif/reindex': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/exif/reindex.post').default>>>>
    }
    '/api/photos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/index.post').default>>>>
    }
    '/api/photos/livephoto/manage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/livephoto/manage.post').default>>>>
    }
    '/api/photos/reactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/reactions.get').default>>>>
    }
    '/api/photos/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/status.get').default>>>>
    }
    '/api/photos/upload': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photos/upload.put').default>>>>
    }
    '/api/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile.get').default>>>>
    }
    '/api/queue/add-task': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/queue/add-task.post').default>>>>
    }
    '/api/queue/add-tasks': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/queue/add-tasks.post').default>>>>
    }
    '/api/queue/stats/:taskId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/queue/stats/[taskId].get').default>>>>
    }
    '/api/queue/stats': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/queue/stats/index').default>>>>
    }
    '/api/queue/task/clear': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/queue/task/clear.delete').default>>>>
    }
    '/api/queue/task/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/queue/task/list.get').default>>>>
    }
    '/api/queue/task/retry-batch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/queue/task/retry-batch.post').default>>>>
    }
    '/api/queue/task/retry': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/queue/task/retry.post').default>>>>
    }
    '/api/system/logs': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/logs').default>>>>
    }
    '/api/system/settings/:namespace': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/settings/[namespace].get').default>>>>
    }
    '/api/system/settings/:namespace/:key': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/settings/[namespace]/[key]').default>>>>
    }
    '/api/system/settings/all': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/settings/all.get').default>>>>
    }
    '/api/system/settings/batch': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/settings/batch.put').default>>>>
    }
    '/api/system/settings/fields': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/settings/fields.get').default>>>>
    }
    '/api/system/settings/schema': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/settings/schema.get').default>>>>
    }
    '/api/system/settings/storage-config/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/settings/storage-config/[id]').default>>>>
    }
    '/api/system/settings/storage-config': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/settings/storage-config/index').default>>>>
    }
    '/api/system/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/stats.get').default>>>>
    }
    '/api/wizard/admin': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wizard/admin.post').default>>>>
    }
    '/api/wizard/complete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wizard/complete.post').default>>>>
    }
    '/api/wizard/map': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wizard/map.post').default>>>>
    }
    '/api/wizard/schema': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wizard/schema.get').default>>>>
    }
    '/api/wizard/site': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wizard/site.post').default>>>>
    }
    '/api/wizard/storage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wizard/storage.post').default>>>>
    }
    '/api/wizard/submit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wizard/submit.post').default>>>>
    }
    '/image/**:key': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/image/[...key].get').default>>>>
    }
    '/storage/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/storage/[...path]').default>>>>
    }
    '/thumb/**:thumbnailUrl': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/thumb/[...thumbnailUrl].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.2.2_ecc391efaa4bd5275b73332700e879f9/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.0.0_magicast@0.5.1_vite@7.3.0_@types+node@22.19.3_jiti@2.6.1_lightningcss@_d3844ef4d7e318d88d196af71143e9ac/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-auth-utils@0.5.23_magicast@0.5.1/node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-auth-utils@0.5.23_magicast@0.5.1/node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/__og-image__/font/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.12_@unhead+vue@2.1.1_vue@3.5.26_typescript@5.9.3___h3@1.15.4_magicast_cc5ffa53446ac9a9d3e84ffe6464de21/node_modules/nuxt-og-image/dist/runtime/server/routes/font').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-site-config@3.2.14_h3@1.15.4_magicast@0.5.1_vue@3.5.26_typescript@5.9.3_/node_modules/nuxt-site-config/dist/runtime/server/routes/__site-config__/debug').default>>>>
    }
    '/__og-image__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.12_@unhead+vue@2.1.1_vue@3.5.26_typescript@5.9.3___h3@1.15.4_magicast_cc5ffa53446ac9a9d3e84ffe6464de21/node_modules/nuxt-og-image/dist/runtime/server/routes/debug.json').default>>>>
    }
    '/__og-image__/image/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.12_@unhead+vue@2.1.1_vue@3.5.26_typescript@5.9.3___h3@1.15.4_magicast_cc5ffa53446ac9a9d3e84ffe6464de21/node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/__og-image__/static/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.12_@unhead+vue@2.1.1_vue@3.5.26_typescript@5.9.3___h3@1.15.4_magicast_cc5ffa53446ac9a9d3e84ffe6464de21/node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/_i18n/:hash/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+i18n@10.1.0_@vue+compiler-dom@3.5.26_db0@0.3.4_better-sqlite3@12.5.0_drizzle-or_9a174711d70ee663b64d175dd292a283/node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+image@1.11.0_db0@0.3.4_better-sqlite3@12.5.0_drizzle-orm@0.44.7_@cloudflare+worke_5886db073ec5b512e225e21b22b6101b/node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}